import { z } from "zod";

export const HomologationScenarioSchema = z.object({
  id: z.string().min(1),
  title: z.string().min(1),
  area: z.enum([
    "auth",
    "cadastro",
    "kits",
    "estoque",
    "entregas",
    "documentos",
    "historico",
    "dashboard",
    "importacao",
    "planejamento",
    "auditoria",
  ]),
  priority: z.enum(["critical", "high", "medium"]),
  actor: z.string().min(1),
  objective: z.string().min(1),
  prerequisites: z.array(z.string().min(1)),
  steps: z.array(z.string().min(1)).min(1),
  expectedResults: z.array(z.string().min(1)).min(1),
  evidence: z.array(z.string().min(1)).min(1),
});

export type HomologationScenario = z.infer<typeof HomologationScenarioSchema>;

export const HOMOLOGATION_SCENARIOS = [
  {
    id: "HMG-01",
    title: "Acesso por perfil e bloqueio de rota restrita",
    area: "auth",
    priority: "critical",
    actor: "Administrador e Operador",
    objective: "Confirmar que perfis acessam somente o que sua permissao permite.",
    prerequisites: ["Usuarios seedados", "Aplicacao em staging acessivel"],
    steps: [
      "Entrar como admin@empresa.com.",
      "Abrir /usuarios e /auditoria.",
      "Sair e entrar como op@empresa.com.",
      "Tentar abrir /usuarios e /auditoria.",
    ],
    expectedResults: [
      "Administrador acessa usuarios e auditoria.",
      "Operador e redirecionado para /unauthorized nas rotas restritas.",
      "Tentativas negadas ficam registradas em auditoria quando aplicavel.",
    ],
    evidence: ["Print da tela autorizada", "Print da tela unauthorized", "Registro de auditoria"],
  },
  {
    id: "HMG-02",
    title: "Cadastro e atualizacao de colaborador com tamanhos",
    area: "cadastro",
    priority: "high",
    actor: "RH / Almoxarifado",
    objective: "Validar cadastro de colaborador com cargo, secretaria e tamanhos operacionais.",
    prerequisites: ["Cargo ativo existente", "Usuario com permissao de colaboradores"],
    steps: [
      "Criar colaborador novo com CPF valido, matricula, secretaria e cargo.",
      "Preencher camiseta, calca e calcado.",
      "Salvar e reabrir a ficha do colaborador.",
      "Editar um tamanho e salvar novamente.",
    ],
    expectedResults: [
      "Colaborador e criado ativo.",
      "Tamanhos aparecem na ficha e afetam planejamento por variante.",
      "Edicao e persistida sem duplicar colaborador.",
    ],
    evidence: ["Print do cadastro salvo", "Print da ficha do colaborador"],
  },
  {
    id: "HMG-03",
    title: "Versionamento de kit por cargo e publicacao",
    area: "kits",
    priority: "critical",
    actor: "Administrador ou RH / Almoxarifado",
    objective: "Confirmar que kits sao versionados e publicados sem sobrepor historico invalido.",
    prerequisites: ["Cargo ativo", "Materiais UNIFORM e PPE ativos"],
    steps: [
      "Abrir /cargos e acessar o kit de um cargo operacional.",
      "Criar nova versao rascunho.",
      "Adicionar um fardamento e um EPI compativel com o cargo.",
      "Publicar a revisao.",
      "Conferir que a versao anterior ficou historica.",
    ],
    expectedResults: [
      "Rascunho aceita edicao de itens.",
      "Publicacao ativa a nova revisao.",
      "Versao anterior recebe fim de vigencia.",
    ],
    evidence: ["Print do rascunho", "Print da revisao publicada", "Historico de versoes"],
  },
  {
    id: "HMG-04",
    title: "Movimentacao de estoque com bloqueio de saldo negativo",
    area: "estoque",
    priority: "critical",
    actor: "RH / Almoxarifado",
    objective: "Garantir que entradas, saidas e ajustes respeitam saldo e ledger.",
    prerequisites: ["Material ativo com saldo conhecido"],
    steps: [
      "Registrar entrada de estoque.",
      "Registrar saida menor que o saldo.",
      "Tentar registrar saida maior que o saldo disponivel.",
    ],
    expectedResults: [
      "Entrada e saida validas atualizam saldo.",
      "Saida maior que saldo e bloqueada com mensagem operacional.",
      "Transacoes ficam registradas no historico de estoque.",
    ],
    evidence: ["Print antes/depois do saldo", "Print do erro de saldo insuficiente"],
  },
  {
    id: "HMG-05",
    title: "Entrega de fardamento com recibo por evento",
    area: "entregas",
    priority: "critical",
    actor: "Operador ou RH / Almoxarifado",
    objective: "Validar baixa de estoque, assignment e recibo individual de fardamento.",
    prerequisites: ["Colaborador ativo", "Kit ativo com item UNIFORM", "Estoque suficiente"],
    steps: [
      "Abrir entregas e selecionar colaborador.",
      "Escolher tipo Fardamento.",
      "Carregar itens do kit e confirmar entrega.",
      "Abrir recibo gerado.",
    ],
    expectedResults: [
      "Entrega e registrada.",
      "Estoque e baixado.",
      "Recibo UNIFORM abre por evento.",
      "Historico do colaborador mostra documento emitido.",
    ],
    evidence: ["Print da entrega", "Print do recibo", "Print do historico"],
  },
  {
    id: "HMG-06",
    title: "Entrega de EPI com ficha historica acumulativa",
    area: "documentos",
    priority: "critical",
    actor: "Operador ou RH / Almoxarifado",
    objective: "Validar separacao juridica entre recibo de fardamento e ficha historica de EPI.",
    prerequisites: ["Colaborador ativo", "Kit ativo com item PPE", "Estoque suficiente"],
    steps: [
      "Registrar entrega do tipo EPI.",
      "Abrir ficha de EPI do colaborador.",
      "Registrar uma segunda entrega de EPI.",
      "Abrir versao anterior da ficha por query string de versao.",
    ],
    expectedResults: [
      "Ficha PPE acumula historico por colaborador.",
      "Versao anterior mostra apenas itens ate a data daquele documento.",
      "Atalho de reimpressao respeita a versao.",
    ],
    evidence: ["Print da ficha atual", "Print da ficha versionada", "Historico do colaborador"],
  },
  {
    id: "HMG-07",
    title: "Importacao em massa com preview e relatorio de erros",
    area: "importacao",
    priority: "high",
    actor: "Administrador ou RH / Almoxarifado",
    objective: "Confirmar importacao guiada com template, validacao e auditoria de lote.",
    prerequisites: ["Arquivo CSV/XLSX de teste", "Usuario com permissao de importacao"],
    steps: [
      "Abrir importacao de colaboradores, materiais ou kits.",
      "Baixar template.",
      "Enviar arquivo com uma linha valida e uma linha invalida.",
      "Validar preview e confirmar importacao.",
      "Abrir historico da importacao.",
    ],
    expectedResults: [
      "Preview classifica linhas validas e invalidas.",
      "Linhas invalidas nao bloqueiam todo o lote quando o fluxo permite.",
      "Historico mostra resumo e amostra do lote.",
    ],
    evidence: ["Arquivo usado", "Print do preview", "Print do historico"],
  },
  {
    id: "HMG-08",
    title: "Dashboard com filtros e pendencias agregadas",
    area: "dashboard",
    priority: "high",
    actor: "Gestor",
    objective: "Validar indicadores, filtros e relatorios agregados de pendencias.",
    prerequisites: ["Base com colaboradores, kits, entregas e estoque"],
    steps: [
      "Abrir /dashboard.",
      "Aplicar filtro de secretaria.",
      "Aplicar filtro de cargo.",
      "Alternar periodo.",
      "Conferir agregados por cargo e secretaria.",
    ],
    expectedResults: [
      "Cards refletem os filtros.",
      "Pendencias e estoque critico mudam conforme o recorte.",
      "Agregados permanecem coerentes com a lista de pendencias.",
    ],
    evidence: ["Print sem filtros", "Print com filtros", "Print dos agregados"],
  },
  {
    id: "HMG-09",
    title: "Planejamento de compras priorizado por risco",
    area: "planejamento",
    priority: "high",
    actor: "Gestor ou RH / Almoxarifado",
    objective: "Validar sugestao de compra considerando estoque, base ativa, tamanhos e consumo.",
    prerequisites: ["Historico operacional minimamente populado"],
    steps: [
      "Abrir /estoque/planejamento.",
      "Conferir consumo historico por variante.",
      "Conferir compra sugerida para base ativa e buffer minimo.",
      "Conferir sinais de admissao, sizing pendente e retorno potencial.",
      "Conferir ranking de risco de ruptura.",
    ],
    expectedResults: [
      "Sugestao mostra decomposicao operacional.",
      "Variantes por tamanho aparecem separadas.",
      "Ranking prioriza itens com maior risco.",
    ],
    evidence: ["Print do planejamento", "Print do ranking priorizado"],
  },
  {
    id: "HMG-10",
    title: "Trilha de auditoria dos fluxos criticos",
    area: "auditoria",
    priority: "critical",
    actor: "Administrador ou Gestor",
    objective:
      "Confirmar rastreabilidade minima de login, importacao, entrega e alteracoes criticas.",
    prerequisites: ["Fluxos anteriores executados no mesmo ambiente"],
    steps: [
      "Abrir /auditoria.",
      "Filtrar visualmente eventos de login.",
      "Conferir eventos de importacao.",
      "Conferir eventos de entrega/documentos.",
      "Conferir eventos de alteracao de kit ou usuario quando aplicavel.",
    ],
    expectedResults: [
      "Eventos criticos aparecem com usuario, acao, entidade e data.",
      "Auditoria contem detalhes suficientes para rastreio operacional.",
    ],
    evidence: ["Print da auditoria", "IDs dos eventos relevantes"],
  },
] satisfies HomologationScenario[];

export function getCriticalHomologationScenarios() {
  return HOMOLOGATION_SCENARIOS.filter((scenario) => scenario.priority === "critical");
}

export function validateHomologationScenarioCatalog() {
  return z.array(HomologationScenarioSchema).parse(HOMOLOGATION_SCENARIOS);
}
